<?xml version="1.0"?>
<package format="3">
  <name>rc_car_control</name>
  <version>0.1.0</version>
  <description>PID heading controller using IMU feedback</description>
  <maintainer email="preyansh@todo.com">Preyansh</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
