<?xml version="1.0"?>
<package format="3">
  <name>rc_car_driver</name>
  <version>0.1.0</version>
  <description>L298N motor driver node for 4WD RC car</description>
  <maintainer email="jenil@gmail.com">Preyansh</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
